//
// Copyright 2025 Munir, LLC
// SPDX-License-Identifier: MIT
//

#import <MunrChatServiceKit/TSErrorMessage.h>

NS_ASSUME_NONNULL_BEGIN

// TODO: Remove this class, clean up existing instances, and ensure any
// missed ones don't explode (UnknownDBObject).

// This is a deprecated class. We're keeping it around to avoid YapDB
// serialization errors.
/* DEPRECATED */ @interface OWSUnknownContactBlockOfferMessage : TSErrorMessage

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run
// `sds_codegen.sh`.


// --- CODE GENERATION MARKER

@end

NS_ASSUME_NONNULL_END
